Dynamic Display of Featured Speakers
Baayeh/dev-summit pull request #3
Opened 2022-09-14 15:21 UTC by Baayeh

- Created an array of objects storing the details of the featured speakers.
- Injected them directly into the HTML file

2022-09-14 18:46 UTC, frank1738 requested changes
Hi @Baayeh , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![YesYouAreGIF (2)](https://user-images.githubusercontent.com/50941074/172881298-64e98170-87c5-4075-8a77-71d65d991f55.gif)


## Highlights

✅ No linter error
✅ README is okay


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

- [OPTIONAL] I noticed that you created three pull requests on various milestones of the project, merged two of them, and submitted the last one for review.  I would highly recommend that you create one branch (`feature branch`), where you push all your changes, and compare it to the main branch as it is a good GitHub flow practice

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 18:46 UTC, frank1738 commented on about.html
>                    <a class="nav-link" href="#" data-text="Attend">Attend</a>
- [ ] Would you please add the missing social links bar to match the Behance design as it is a project requirement

### Behance design
![image](https://user-images.githubusercontent.com/98453979/190227021-636763dd-d197-4d2b-b77f-953bc94cc4a7.png)

### your design

![image](https://user-images.githubusercontent.com/98453979/190227258-381a3ec1-7d3e-4266-a62c-aeeba4e9da64.png)

- [ ] Your `about` section is missing three sections. Would you please add them to match the Behance design

### The middle section
![image](https://user-images.githubusercontent.com/98453979/190233011-eb763dcb-be8e-407f-a3a2-a63cb7297c46.png)

### Bottom section

![image](https://user-images.githubusercontent.com/98453979/190233277-3ea3ee94-e83a-4db3-acd5-b3c625134433.png)

### Footer

![image](https://user-images.githubusercontent.com/98453979/190233489-7606acbb-14a1-404a-876b-9f0540494fa5.png)


### Your Design

![image](https://user-images.githubusercontent.com/98453979/190233827-c4c04e0d-ecd5-4c84-9962-edcb22a539e0.png)

2022-09-15 04:56 UTC, Bondok6 requested changes
## Hi @Baayeh 🙋‍♂️, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

 ## Required Changes ♻️
- [ ] _Check the comments under the review._ ⬇

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 04:56 UTC, Bondok6 commented on about.html
> +    </footer>
- [ ] The footer section should has a white background on mobile version, Kindly fix it 💯
- [OPTIONAL] It would be better to add the partners section also on mobile version 👌

> Original Design 
![image](https://user-images.githubusercontent.com/45231276/190316863-3cd0c709-5ac1-4eff-b937-998f3a16a2ba.png)

2022-09-15 04:56 UTC, Bondok6 commented on about.html
> +    </section>
- [ ] According to the requirements, You should follow the [original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), Colors. Typography, Layout 💯, So kindly this section should include a section header, a divider, a line of text, and two images with text centered over them.

>This section should look almost identical to the original design, outside the content differences. 👌

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/190316343-af37e438-fc32-43c1-9e81-17804ed81974.PNG" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/190316364-e67fc3d9-1c5a-4ca0-b688-b75455306ff8.PNG" width="500" /> |

2022-09-15 04:56 UTC, Bondok6 commented on about.html
> +    </section>
- [ ] This section should contain an image or large logo to look similar to the original design, kindly add is 💯

| Your Design  | Original Design  |   
| --- | --- |
| <img src="https://user-images.githubusercontent.com/45231276/190317619-5676dcee-8701-4f39-9c93-229994a39f56.png" width="500" />  | <img src="https://user-images.githubusercontent.com/45231276/190317545-c4a4e4fb-a6dc-4055-9861-3cd28e5b1913.png" width="500" /> |

2022-09-15 18:37 UTC, Ugboaja-Uchechi approved these changes
Hi @Baayeh , 

## Status: APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- Linters are passing ✔️ 
- README is descriptive 👍 
- Great job with your design and functionalities 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 18:38 UTC, merged